on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: openjdk:11.0.1-jdk-slim-stretch
    name: Build and test
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: Dump GitHub context vars
        run: | 
          echo "github.sha: ${{ github.sha }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
      # Reference: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context
      - name: Set Git branch for Code Climate
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]
          then 
            echo ::set-env name=GIT_BRANCH::${{ github.head_ref }}
          else
            echo ::set-env name=GIT_BRANCH::$(echo $GITHUB_REF | cut -c12-)
          fi
      - uses: actions/checkout@v1
      - name: Setup Code Climate tool
        run: |
          apt-get update && apt-get install -y curl git
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter 
      - name: Before tests
        run: ./cc-test-reporter before-build
      - name: Test
        run: ./gradlew test
      - name: Publish test coverage
        run: | 
          ./gradlew testCoverage
          JACOCO_SOURCE_PATH=src/main/kotlin ./cc-test-reporter format-coverage -t jacoco ./build/reports/jacoco/test/jacocoTestReport.xml
          ./cc-test-reporter upload-coverage
