on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: openjdk:11.0.1-jdk-slim-stretch
    name: Build and test
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      GIT_BRANCH: ${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Code Climate tool
        run: |
          apt-get update && apt-get install -y curl git
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter 
      - name: Before tests
        run: ./cc-test-reporter before-build
      - name: Test
        run: ./gradlew test
      - name: Publish test coverage
        run: | 
          ./gradlew testCoverage
          JACOCO_SOURCE_PATH=src/main/kotlin ./cc-test-reporter format-coverage -t jacoco ./build/reports/jacoco/test/jacocoTestReport.xml
          ./cc-test-reporter upload-coverage
