on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: openjdk:11.0.1-jdk-slim-stretch
    name: Build and test
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: ./gradlew test
      - name: Publish test coverage
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
        with:
          coverageCommand: ./gradlew testCoverage
          coverageLocations: "build/reports/jacoco/test/jacocoTestReport.xml" 
    
