on: [pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: codeclimate/codeclimate
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - name: Run analysis
        run: codeclimate analyze > analysis.txt
      - name: Persist analysis file
        uses: actions/upload-artifact@v1
        with:
          name: analysis
          path: ./analysis.txt
